version: '3.8'

services:
  ###> doctrine/doctrine-bundle ###
  database:
    container_name: quarters_mysql
    image: library/mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quarters_dev
      MYSQL_PASSWORD: root
    ports:
      - '4306:3306'
    volumes:
      - ./docker/mysql:/var/lib/mysql
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--innodb-flush-method=fsync', '--default-authentication-plugin=mysql_native_password' ]

  php:
    container_name: quarters_php
    build:
      context: docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./:/app
    depends_on:
      - database

  nginx:
    container_name: quarters_nginx
    image: library/nginx:stable
    ports:
      - '8000:80'
    volumes:
      - ./:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

  composer:
    container_name: quarters_composer
    image: library/composer:2
    volumes:
      - ./:/app
    depends_on:
      - php
      - database
      - nginx
    command: bash -c "composer install && php bin/console assets:install"

volumes:
  ###> doctrine/doctrine-bundle ###
  db-data:
  ###< doctrine/doctrine-bundle ###
